import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { Modal } from '../ui/Modal';
import { Input } from '../ui/Input';
import { Button } from '../ui/Button';
import { useCreateRole } from '../../hooks/useRoles';
import { useI18n } from '../../i18n/useI18n';

interface Props {
  isOpen: boolean;
  onClose: () => void;
}

interface FormData {
  name: string;
  description: string;
}

function toCode(name: string): string {
  return name
    .toUpperCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^A-Z0-9\s]/g, '')
    .trim()
    .replace(/\s+/g, '_');
}

export function CreateRoleModal({ isOpen, onClose }: Props) {
  const { t } = useI18n();
  const createRole = useCreateRole();
  const [serverError, setServerError] = useState('');

  const {
    register,
    handleSubmit,
    watch,
    reset,
    formState: { errors },
  } = useForm<FormData>({ defaultValues: { name: '', description: '' } });

  const nameValue = watch('name');
  const codePreview = toCode(nameValue || '');

  const onSubmit = async (data: FormData) => {
    setServerError('');
    try {
      await createRole.mutateAsync({ name: data.name, description: data.description || undefined });
      reset();
      onClose();
    } catch (err: unknown) {
      const e = err as { response?: { data?: { message?: string } } };
      const msg = e.response?.data?.message || t('messages.error');
      if (msg.toLowerCase().includes('đã tồn tại') || msg.toLowerCase().includes('exists')) {
        setServerError(t('roles.validation.codeExists'));
      } else {
        setServerError(msg);
      }
    }
  };

  const handleClose = () => {
    reset();
    setServerError('');
    onClose();
  };

  return (
    <Modal isOpen={isOpen} onClose={handleClose} title={t('roles.addRole')} size="md">
      <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
        {serverError && (
          <div className="p-3 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg text-sm text-red-700 dark:text-red-400">
            {serverError}
          </div>
        )}

        <Input
          label={t('roles.roleName') + ' *'}
          placeholder="VD: Kế Toán Trưởng"
          error={errors.name?.message}
          {...register('name', {
            required: t('roles.validation.nameRequired'),
            minLength: { value: 2, message: t('roles.validation.nameMinLength') },
            maxLength: { value: 100, message: t('roles.validation.nameMaxLength') },
          })}
        />

        <div>
          <label className="block text-sm font-medium text-neutral-700 dark:text-neutral-300 mb-1.5">
            {t('roles.roleCode')} ({t('roles.codeAutoGenerated')})
          </label>
          <div className="px-3 py-2 border border-neutral-200 dark:border-neutral-700 rounded-lg bg-neutral-50 dark:bg-neutral-800 text-sm font-mono text-neutral-500 dark:text-neutral-400">
            {codePreview || '—'}
          </div>
        </div>

        <div>
          <label className="block text-sm font-medium text-neutral-700 dark:text-neutral-300 mb-1.5">
            {t('roles.roleDescription')}
          </label>
          <textarea
            className="w-full px-3 py-2 border border-neutral-300 dark:border-neutral-600 rounded-lg text-neutral-900 dark:text-neutral-100 bg-white dark:bg-neutral-800 focus:outline-none focus:ring-2 focus:ring-neutral-500 focus:border-transparent text-sm resize-none"
            rows={3}
            placeholder={t('roles.roleDescription') + '...'}
            {...register('description', {
              maxLength: { value: 500, message: t('roles.validation.descriptionMaxLength') },
            })}
          />
          {errors.description?.message && (
            <p className="mt-1 text-sm text-red-600">{errors.description.message}</p>
          )}
        </div>

        <div className="flex justify-end gap-3 pt-2">
          <Button type="button" variant="outline" onClick={handleClose}>
            {t('createUser.cancel')}
          </Button>
          <Button type="submit" isLoading={createRole.isPending}>
            {t('roles.addRole')}
          </Button>
        </div>
      </form>
    </Modal>
  );
}
